title: Document Rotator
description: This Add-On will detect the orientation of pages in a document, detect their approximate skew angle, and rotate the pages for you automatically. It will upload the modified document as a new document, preserving the original.
instructions: ''
type: object
documents:
  - selected
properties:
  project_id:
    title: Project ID of the project you would like the documents uploaded to (optional)
    type: integer
  access_level:
    title: Access level for uploaded documents (public, private(default), organization)
    type: string
    default: private
categories:
  - file
