title: Document Rotator
description: This Add-On will detect the orientation of pages in a document, detect their approximate skew angle, and rotate the pages for you automatically. It will upload the modified document as a new document, preserving the original.
instructions: ''
type: object
documents:
  - selected
properties:
  name:
    title: Name
    type: string
categories:
  - file
